// Generated by CoffeeScript 1.6.3
(function() {
  define(['plugins/router', 'jquery', 'q'], function(router, $, Q) {
    var moduleId, route, routes, routesArray;
    routes = {
      'user/verifyemail/:email/:token': 'views/user/verifyemail',
      'user/:username': 'views/user/dashboard'
    };
    routesArray = (function() {
      var _results;
      _results = [];
      for (route in routes) {
        moduleId = routes[route];
        _results.push({
          route: route,
          moduleId: moduleId
        });
      }
      return _results;
    })();
    router.map(routesArray);
    return {
      getUser: function(username) {
        return Q($.get('/blackbeard/user', {
          username: username
        }));
      }
    };
  });

}).call(this);
