// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout'], function(ko) {
    var Output;
    return Output = (function() {
      function Output() {
        this.showInfo = __bind(this.showInfo, this);
        this.forward = __bind(this.forward, this);
        this.back = __bind(this.back, this);
        this.activate = __bind(this.activate, this);
        this.feedback = ko.observable(null);
        this.output = ko.observable(null);
        this.isShowingInfo = ko.observable(false);
      }

      Output.prototype.activate = function(options) {
        var activationData;
        this.wizard = options.wizard, activationData = options.activationData;
        this.feedback(activationData);
        if (this.feedback().feedback.output != null) {
          return this.output(this.feedback().feedback.output);
        } else {
          return this.output(0.05);
        }
      };

      Output.prototype.back = function() {
        var options;
        this.feedback().feedback.output = this.output();
        options = {
          model: 'views/feedback/give/1-skill',
          activationData: this.feedback()
        };
        return this.wizard.back(options)();
      };

      Output.prototype.forward = function() {
        var options;
        this.feedback().feedback.output = this.output();
        options = {
          model: 'views/feedback/give/3-delivery',
          activationData: this.feedback()
        };
        return this.wizard.forward(options)();
      };

      Output.prototype.showInfo = function() {
        return this.isShowingInfo(true);
      };

      return Output;

    })();
  });

}).call(this);
