// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/express/configure', 'odo/durandal/plugin'], function(module, configure, durandal) {
    var Welcome;
    return Welcome = (function() {
      function Welcome() {
        this.web = __bind(this.web, this);
      }

      Welcome.prototype.web = function() {
        configure.route('/views', configure.modulepath(module.uri) + '/public');
        return durandal.register('views/welcome');
      };

      return Welcome;

    })();
  });

}).call(this);
