// Generated by CoffeeScript 1.6.3
(function() {
  var requirejs,
    __slice = [].slice;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      odo: './node_modules/odo',
      local: './'
    }
  });

  requirejs(['odo/infra/hub', 'odo/user/usercommands', 'local/feedback/feedbackcommands'], function() {
    var hub, plugin, plugins, _i, _len, _results;
    hub = arguments[0], plugins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    plugins = plugins.map(function(plugin) {
      if (typeof plugin === 'function') {
        return new plugin;
      }
      return plugin;
    });
    _results = [];
    for (_i = 0, _len = plugins.length; _i < _len; _i++) {
      plugin = plugins[_i];
      if (plugin.domain != null) {
        _results.push(plugin.domain());
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
