// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout', 'odo/auth', 'odo/auth/current-user'], function(ko, auth, user) {
    var GoogleProfile;
    return GoogleProfile = (function() {
      function GoogleProfile() {
        this.back = __bind(this.back, this);
        this.disconnect = __bind(this.disconnect, this);
        this.stopDisconnect = __bind(this.stopDisconnect, this);
        this.startDisconnect = __bind(this.startDisconnect, this);
        this.activate = __bind(this.activate, this);
        this.user = ko.observable(null);
      }

      GoogleProfile.prototype.activate = function(options) {
        this.wizard = options.wizard, this.dialog = options.dialog;
        return this.user(user);
      };

      GoogleProfile.prototype.disconnectStarted = ko.observable(false);

      GoogleProfile.prototype.startDisconnect = function() {
        return this.disconnectStarted(true);
      };

      GoogleProfile.prototype.stopDisconnect = function() {
        return this.disconnectStarted(false);
      };

      GoogleProfile.prototype.disconnect = function() {
        return auth.disconnectGoogleFromUser(this.user().id, this.user().google.profile).then((function(_this) {
          return function() {
            return _this.back();
          };
        })(this));
      };

      GoogleProfile.prototype.back = function() {
        return this.wizard.back({
          model: 'views/user/profile/review'
        })();
      };

      return GoogleProfile;

    })();
  });

}).call(this);
