// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout', 'odo/inject', 'odo/auth/current-user'], function(ko, inject, currentUser) {
    var DashboardOther;
    return DashboardOther = (function() {
      DashboardOther.prototype.widgets = inject.many('user/dashboard-other/widgets');

      function DashboardOther() {
        this.activate = __bind(this.activate, this);
        this.title = ko.observable('');
        this.viewingUser = ko.observable(null);
        this.dashboardUser = ko.observable(null);
      }

      DashboardOther.prototype.activate = function(activationData) {
        var dashboardUser;
        dashboardUser = activationData.dashboardUser;
        this.viewingUser(currentUser);
        return this.dashboardUser(dashboardUser);
      };

      return DashboardOther;

    })();
  });

}).call(this);
