// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout', 'q', 'odo/inject', 'odo/auth/current-user'], function(ko, Q, inject, currentUser) {
    var DashboardSelf;
    return DashboardSelf = (function() {
      DashboardSelf.prototype.inwidgets = inject.many('user/dashboard-self/in-widgets');

      DashboardSelf.prototype.outwidgets = inject.many('user/dashboard-self/out-widgets');

      function DashboardSelf() {
        this.activate = __bind(this.activate, this);
        this.title = ko.observable('');
        this.viewingUser = ko.observable(null);
        this.dashboardUser = ko.observable(null);
      }

      DashboardSelf.prototype.activate = function(activationData) {
        var dashboardUser;
        dashboardUser = activationData.dashboardUser;
        this.viewingUser(currentUser);
        return this.dashboardUser(dashboardUser);
      };

      return DashboardSelf;

    })();
  });

}).call(this);
