// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['knockout', 'odo/inject', 'odo/auth/current-user'], function(ko, inject, currentUser) {
    var DashboardOther;
    return DashboardOther = (function() {
      function DashboardOther() {
        this.activate = __bind(this.activate, this);
      }

      DashboardOther.prototype.widgets = inject.many('user/dashboard-other/widgets');

      DashboardOther.prototype.title = ko.observable('');

      DashboardOther.prototype.viewingUser = ko.observable(null);

      DashboardOther.prototype.dashboardUser = ko.observable(null);

      DashboardOther.prototype.activate = function(activationData) {
        var dashboardUser;
        dashboardUser = activationData.dashboardUser;
        this.viewingUser(currentUser);
        return this.dashboardUser(dashboardUser);
      };

      return DashboardOther;

    })();
  });

}).call(this);
