// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['q', 'knockout', 'odo/auth', 'user', 'odo/inject'], function(Q, ko, auth, user, inject) {
    var UserDashboard;
    return UserDashboard = (function() {
      function UserDashboard() {
        this.activate = __bind(this.activate, this);
        this.canActivate = __bind(this.canActivate, this);
      }

      UserDashboard.prototype.widgets = inject.many('user/dashboard/widgets');

      UserDashboard.prototype.title = ko.observable('');

      UserDashboard.prototype.user = ko.observable(null);

      UserDashboard.prototype.canActivate = function(username) {
        var dfd,
          _this = this;
        dfd = Q.defer();
        user.getUser(username).then(function(user) {
          return dfd.resolve(true);
        }).fail(function(err) {
          return dfd.resolve(false);
        });
        return dfd.promise;
      };

      UserDashboard.prototype.activate = function(username) {
        var dfd,
          _this = this;
        dfd = Q.defer();
        user.getUser(username).then(function(user) {
          _this.user(user);
          return dfd.resolve();
        }).fail(function(err) {
          return dfd.resolve();
        });
        return dfd.promise;
      };

      return UserDashboard;

    })();
  });

}).call(this);
