// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['knockout'], function(ko) {
    var Profile;
    return Profile = (function() {
      function Profile() {
        this.activate = __bind(this.activate, this);
      }

      Profile.prototype.composeOptions = ko.observable(null);

      Profile.prototype.activate = function(options) {
        this.dialog = options.dialog;
        return this.composeOptions({
          model: 'components/wizard',
          activationData: {
            dialog: this.dialog,
            model: 'views/user/profile/review'
          }
        });
      };

      return Profile;

    })();
  });

}).call(this);
