// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['q', 'knockout', 'odo/auth', 'odo/auth/current-user', 'components/dialog'], function(Q, ko, auth, user, Dialog) {
    var VerifyEmail;
    return VerifyEmail = (function() {
      function VerifyEmail() {
        this.showProfile = __bind(this.showProfile, this);
        this.activate = __bind(this.activate, this);
        this.title = ko.observable('');
        this.isTokenValid = ko.observable(false);
        this.result = ko.observable(null);
        this.email = ko.observable(null);
        this.token = ko.observable(null);
        this.user = ko.observable(null);
      }

      VerifyEmail.prototype.activate = function(email, token) {
        var dfd;
        this.email(email);
        this.token(token);
        this.title("Verifying " + email);
        dfd = Q.defer();
        auth.checkEmailVerificationToken(this.email(), this.token()).then((function(_this) {
          return function(result) {
            _this.isTokenValid(result.isValid);
            _this.result(result);
            return auth.assignEmailAddressToUserWithToken(_this.email(), _this.token()).then(function() {
              _this.user(user);
              return dfd.resolve(true);
            });
          };
        })(this)).fail((function(_this) {
          return function() {
            return dfd.resolve(false);
          };
        })(this));
        return dfd.promise;
      };

      VerifyEmail.prototype.showProfile = function() {
        return new Dialog({
          model: 'views/user/profile'
        }).show();
      };

      return VerifyEmail;

    })();
  });

}).call(this);
