// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout', 'odo/auth', 'odo/auth/current-user'], function(ko, auth, user) {
    var ChangeDisplayName;
    return ChangeDisplayName = (function() {
      function ChangeDisplayName() {
        this.changeDisplayName = __bind(this.changeDisplayName, this);
        this.back = __bind(this.back, this);
        this.activate = __bind(this.activate, this);
        this.user = ko.observable(null);
        this.displayName = ko.observable('').extend({
          required: true
        });
        this.errors = ko.validation.group(this);
      }

      ChangeDisplayName.prototype.activate = function(options) {
        this.wizard = options.wizard, this.dialog = options.dialog;
        this.user(user);
        return this.displayName(user.displayName);
      };

      ChangeDisplayName.prototype.back = function() {
        return this.wizard.back({
          model: 'views/user/profile/review'
        })();
      };

      ChangeDisplayName.prototype.changeDisplayName = function() {
        if (this.isValidating()) {
          return;
        }
        if (!this.isValid()) {
          this.dialog.shake();
          this.errors.showAllMessages();
          return;
        }
        if (this.user().displayName === this.displayName()) {
          this.back();
        }
        return auth.assignDisplayNameToUser(this.user().id, this.displayName()).then((function(_this) {
          return function() {
            return _this.back();
          };
        })(this));
      };

      return ChangeDisplayName;

    })();
  });

}).call(this);
