// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['knockout'], function(ko) {
    var ChangeEmailResult;
    return ChangeEmailResult = (function() {
      function ChangeEmailResult() {
        this.back = __bind(this.back, this);
        this.activate = __bind(this.activate, this);
        this.email = ko.observable(null);
      }

      ChangeEmailResult.prototype.activate = function(options) {
        var activationData;
        this.wizard = options.wizard, this.dialog = options.dialog, activationData = options.activationData;
        return this.email(activationData.email);
      };

      ChangeEmailResult.prototype.back = function() {
        return this.wizard.back({
          model: 'views/user/profile/review'
        })();
      };

      return ChangeEmailResult;

    })();
  });

}).call(this);
