// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['knockout', 'odo/auth/current-user', 'components/dialog'], function(ko, user, Dialog) {
    var ReviewProfile;
    return ReviewProfile = (function() {
      function ReviewProfile() {
        this.signuplocal = __bind(this.signuplocal, this);
        this.close = __bind(this.close, this);
        this.activate = __bind(this.activate, this);
        this.user = ko.observable(null);
      }

      ReviewProfile.prototype.activate = function(options) {
        this.wizard = options.wizard, this.dialog = options.dialog;
        return this.user(user);
      };

      ReviewProfile.prototype.close = function() {
        return this.dialog.close();
      };

      ReviewProfile.prototype.signuplocal = function() {
        var options;
        this.close();
        options = {
          model: 'views/auth/localsignup'
        };
        return new Dialog(options).show();
      };

      return ReviewProfile;

    })();
  });

}).call(this);
