// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'redis', 'odo/user/userprofile'], function(module, redis, UserProfile) {
    var User, db;
    db = redis.createClient();
    return User = (function() {
      function User() {
        this.init = __bind(this.init, this);
        this.receive = __bind(this.receive, this);
      }

      User.prototype.receive = function(hub) {
        var _this = this;
        return hub.receive('userHasUsername', function(event, cb) {
          return db.hset('blackbeard:username', event.payload.username, event.payload.id, cb);
        });
      };

      User.prototype.get = function(username, callback) {
        var _this = this;
        return db.hget('blackbeard:username', username, function(err, userid) {
          if (err != null) {
            console.log(err);
            callback(err);
            return;
          }
          return new UserProfile().get(userid, function(err, user) {
            if (err != null) {
              console.log(err);
              callback(err);
              return;
            }
            return callback(null, {
              displayName: user.displayName,
              username: user.username
            });
          });
        });
      };

      User.prototype.configure = function(app) {
        app.route('/', app.modulepath(module.uri) + '/user-public');
        return app.durandal('user');
      };

      User.prototype.init = function(app) {
        var _this = this;
        return app.get('/blackbeard/user', function(req, res) {
          if (req.query.username == null) {
            res.send('Username required');
            return;
          }
          return _this.get(req.query.username, function(err, user) {
            if (err != null) {
              console.log(err);
              res.send(500, 'Woops');
              return;
            }
            if (user == null) {
              res.send(404, 'User not found');
              return;
            }
            return res.send(user);
          });
        });
      };

      return User;

    })();
  });

}).call(this);
