// Generated by CoffeeScript 1.6.3
(function() {
  define(['module'], function(module) {
    var Welcome;
    return Welcome = (function() {
      function Welcome() {}

      Welcome.prototype.configure = function(app) {
        app.route('/views', app.modulepath(module.uri) + '/welcome-public');
        return app.durandal('views/welcome');
      };

      return Welcome;

    })();
  });

}).call(this);
