// Generated by CoffeeScript 1.6.3
(function() {
  define(['odo/eventstore', 'blackbeard/domain/feedback'], function(es, Feedback) {
    var defaultHandler;
    defaultHandler = function(command) {
      var feedback;
      feedback = new Feedback(command.payload.id);
      es.extend(feedback);
      return feedback.applyHistoryThenCommand(command);
    };
    return {
      beginFeedback: defaultHandler,
      cancelFeedback: defaultHandler,
      completeFeedback: defaultHandler
    };
  });

}).call(this);
