// Generated by CoffeeScript 1.6.3
(function() {
  define(['odo/eventstore', 'local/domain/feedback'], function(es, Feedback) {
    var defaultHandler;
    defaultHandler = function(command) {
      var feedback;
      feedback = new Feedback(command.payload.id);
      es.extend(feedback);
      return feedback.applyHistoryThenCommand(command);
    };
    return {
      handle: function(hub) {
        var command, commands, _i, _len, _results;
        commands = ['beginFeedback', 'cancelFeedback', 'completeFeedback'];
        _results = [];
        for (_i = 0, _len = commands.length; _i < _len; _i++) {
          command = commands[_i];
          _results.push(hub.handle(command, defaultHandler));
        }
        return _results;
      }
    };
  });

}).call(this);
