// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['q', 'jquery', 'knockout', 'odo/auth'], function(Q, $, ko, auth) {
    var ChangeDisplayName;
    return ChangeDisplayName = (function() {
      ChangeDisplayName.prototype.user = ko.observable(null);

      function ChangeDisplayName() {
        this.changeDisplayName = __bind(this.changeDisplayName, this);
        this.back = __bind(this.back, this);
        this.activate = __bind(this.activate, this);
        this.displayName = ko.observable('').extend({
          required: true
        });
        this.errors = ko.validation.group(this);
      }

      ChangeDisplayName.prototype.activate = function(options) {
        var dfd,
          _this = this;
        this.wizard = options.wizard, this.dialog = options.dialog;
        dfd = Q.defer();
        auth.getUser().then(function(user) {
          _this.user(user);
          _this.displayName(user.displayName);
          return dfd.resolve(true);
        }).fail(function(err) {
          return dfd.resolve(true);
        });
        return dfd.promise;
      };

      ChangeDisplayName.prototype.back = function() {
        return this.wizard.back({
          model: 'views/user/profile/review'
        })();
      };

      ChangeDisplayName.prototype.changeDisplayName = function() {
        var _this = this;
        if (this.isValidating()) {
          return;
        }
        if (!this.isValid()) {
          this.dialog.shake();
          this.errors.showAllMessages();
          return;
        }
        if (this.user().displayName === this.displayName()) {
          this.back();
        }
        return auth.assignDisplayNameToUser(this.user().id, this.displayName()).then(function() {
          return _this.back();
        });
      };

      return ChangeDisplayName;

    })();
  });

}).call(this);
