// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/express/configure', 'odo/durandal/plugin'], function(module, configure, durandal) {
    var LunchboxSlab;
    return LunchboxSlab = (function() {
      function LunchboxSlab() {
        this.web = __bind(this.web, this);
      }

      LunchboxSlab.prototype.web = function() {
        return configure.route('/lunchboxslab', configure.modulepath(module.uri) + '/public');
      };

      return LunchboxSlab;

    })();
  });

}).call(this);
