// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['odo/messaging/hub', 'odo/messaging/eventstore', 'local/feedback/feedback'], function(hub, es, Feedback) {
    var FeedbackCommands;
    return FeedbackCommands = (function() {
      function FeedbackCommands() {
        this.domain = __bind(this.domain, this);
        this.defaultHandler = __bind(this.defaultHandler, this);
      }

      FeedbackCommands.prototype.commands = ['beginFeedback', 'cancelFeedback', 'completeFeedback'];

      FeedbackCommands.prototype.defaultHandler = function(command) {
        var feedback;
        feedback = new Feedback(command.payload.id);
        es.extend(feedback);
        return feedback.applyHistoryThenCommand(command);
      };

      FeedbackCommands.prototype.domain = function() {
        var command, _i, _len, _ref, _results;
        _ref = this.commands;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          command = _ref[_i];
          _results.push(hub.handle(command, this.defaultHandler));
        }
        return _results;
      };

      return FeedbackCommands;

    })();
  });

}).call(this);
