// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/express/configure', 'odo/durandal/plugin', 'odo/plugins', 'local/feedback/feedback-opportunity-commands', 'local/feedback/user-feedback-widget', 'local/feedback/view-feedback-opportunity'], function() {
    var FeedbackPlugin, Plugins, configure, durandal, module, plugins;
    module = arguments[0], configure = arguments[1], durandal = arguments[2], Plugins = arguments[3], plugins = 5 <= arguments.length ? __slice.call(arguments, 4) : [];
    return FeedbackPlugin = (function() {
      function FeedbackPlugin() {
        this.projection = __bind(this.projection, this);
        this.domain = __bind(this.domain, this);
        this.web = __bind(this.web, this);
      }

      FeedbackPlugin.prototype.web = function() {
        configure.route('/views/feedback', configure.modulepath(module.uri) + '/views');
        durandal.register('views/feedback/bindings');
        return new Plugins(plugins).web();
      };

      FeedbackPlugin.prototype.domain = function() {
        return new Plugins(plugins).domain();
      };

      FeedbackPlugin.prototype.projection = function() {
        return new Plugins(plugins).projection();
      };

      return FeedbackPlugin;

    })();
  });

}).call(this);
