// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['plugins/widget', 'knockout', 'md5'], function(widget, ko, md5) {
    var Avatar;
    widget.registerKind('avatar');
    return Avatar = (function() {
      function Avatar() {
        this.activate = __bind(this.activate, this);
      }

      Avatar.prototype.user = ko.observable(null);

      Avatar.prototype.activate = function(settings) {
        var _this = this;
        this.user(settings.user);
        return this.gravatarHash = ko.computed(function() {
          if ((_this.user() != null) && (_this.user().email != null)) {
            return md5(_this.user().email.trim().toLowerCase());
          }
          return '';
        }, this);
      };

      return Avatar;

    })();
  });

}).call(this);
