// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defineQ(['user', 'plugins/widget', 'knockout'], function(user, widget, ko) {
    var Avatar;
    widget.registerKind('avatar');
    return Avatar = (function() {
      Avatar.prototype.user = ko.observable(null);

      function Avatar() {
        this.activate = __bind(this.activate, this);
        this.gravatarHash = ko.computed((function(_this) {
          return function() {
            if ((_this.user() != null) && (_this.user().emailHash != null)) {
              return _this.user().emailHash;
            }
          };
        })(this), this);
      }

      Avatar.prototype.activate = function(settings) {
        return user.getUser(settings.username).then((function(_this) {
          return function(user) {
            return _this.user(user);
          };
        })(this)).done();
      };

      return Avatar;

    })();
  });

}).call(this);
