// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var SigninLocal;
    return SigninLocal = (function() {
      function SigninLocal() {
        this.canActivate = __bind(this.canActivate, this);
      }

      SigninLocal.prototype.canActivate = function() {
        return {
          redirect: '#'
        };
      };

      return SigninLocal;

    })();
  });

}).call(this);
