// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/infra/hub', 'odo/express/configure', 'odo/express/app', 'odo/durandal/plugin', 'redis', 'odo/user/userprofile'], function(module, hub, configure, app, durandal, redis, UserProfile) {
    var User, db;
    db = redis.createClient();
    return User = (function() {
      function User() {
        this.user = __bind(this.user, this);
        this.projections = __bind(this.projections, this);
        this.web = __bind(this.web, this);
      }

      User.prototype.web = function() {
        configure.route('/', configure.modulepath(module.uri) + '/public');
        durandal.register('user');
        return app.get('/blackbeard/user', this.user);
      };

      User.prototype.projections = function() {
        var _this = this;
        return hub.receive('userHasUsername', function(event, cb) {
          return db.hset('blackbeard:username', event.payload.username, event.payload.id, cb);
        });
      };

      User.prototype.user = function(req, res) {
        var _this = this;
        if (req.query.username == null) {
          res.send('Username required');
          return;
        }
        return this.get(req.query.username, function(err, user) {
          if (err != null) {
            console.log(err);
            res.send(500, 'Woops');
            return;
          }
          if (user == null) {
            res.send(404, 'User not found');
            return;
          }
          return res.send(user);
        });
      };

      User.prototype.get = function(username, callback) {
        var _this = this;
        return db.hget('blackbeard:username', username, function(err, userid) {
          if (err != null) {
            console.log(err);
            callback(err);
            return;
          }
          return new UserProfile().get(userid, function(err, user) {
            if (err != null) {
              console.log(err);
              callback(err);
              return;
            }
            return callback(null, {
              displayName: user.displayName,
              username: user.username
            });
          });
        });
      };

      return User;

    })();
  });

}).call(this);
